[build-system]
requires = ["wheel", "setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

# [tool.setuptools_scm]
# write_to = "autolamella/_version.py"

[project]
name = "autolamella"
version = "0.2.4a1"
description = "Automatated ion beam milling for cryo-electron microscopy sample preparation."
long_description = "file: README.md"
authors = [
    {name = "Patrick Cleeve", email = "Patrick.Cleeve@monash.edu"},
]

license = "MIT"
readme = "README.md"
requires-python = "3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
    ]
dynamic = ["version", "description", "urls", "entry-points"]
dependencies = [
    "fibsem>=0.2.4",
]

[project.scripts]
autolamella_ui = "autolamella.ui.AutoLamellaUI:main"
autoliftout_ui = "autolamella.liftout.ui.AutoLiftoutUIv2:main"

[project.urls]
"Source Code" = "https://github.com/DeMarcoLab/autolamella"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["autolamella*"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
filterwarnings = "ignore::pytest.PytestCacheWarning"

[tool.black]
line-length = 120
target_version = ['py39']