# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 850)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("background-color rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 481, 471))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.General = QtWidgets.QWidget()
        self.General.setObjectName("General")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.General)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 90, 471, 125))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 4, QtCore.Qt.AlignLeft)
        self.hfw_box = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.hfw_box.setMinimum(50)
        self.hfw_box.setMaximum(5000)
        self.hfw_box.setObjectName("hfw_box")
        self.gridLayout_2.addWidget(self.hfw_box, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 1, 3, 1, 1)
        self.RefImage = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.RefImage.setObjectName("RefImage")
        self.gridLayout_2.addWidget(self.RefImage, 2, 0, 1, 2)
        self.gridLayoutWidget = QtWidgets.QWidget(self.General)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 240, 471, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.show_lamella = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.show_lamella.setObjectName("show_lamella")
        self.gridLayout.addWidget(self.show_lamella, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.General)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 461, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ConnectButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ConnectButton.setObjectName("ConnectButton")
        self.horizontalLayout.addWidget(self.ConnectButton)
        self.DisconnectButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.DisconnectButton.setObjectName("DisconnectButton")
        self.horizontalLayout.addWidget(self.DisconnectButton)
        self.tabWidget.addTab(self.General, "")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 470, 441, 271))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.microscope_status = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.microscope_status.setText("")
        self.microscope_status.setAlignment(QtCore.Qt.AlignCenter)
        self.microscope_status.setObjectName("microscope_status")
        self.verticalLayout_2.addWidget(self.microscope_status)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.CLog = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.CLog.setText("")
        self.CLog.setObjectName("CLog")
        self.verticalLayout_2.addWidget(self.CLog)
        self.CLog2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.CLog2.setText("")
        self.CLog2.setObjectName("CLog2")
        self.verticalLayout_2.addWidget(self.CLog2)
        self.CLog3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.CLog3.setText("")
        self.CLog3.setObjectName("CLog3")
        self.verticalLayout_2.addWidget(self.CLog3)
        self.CLog4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.CLog4.setText("")
        self.CLog4.setObjectName("CLog4")
        self.verticalLayout_2.addWidget(self.CLog4)
        self.CLog5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.CLog5.setText("")
        self.CLog5.setObjectName("CLog5")
        self.verticalLayout_2.addWidget(self.CLog5)
        self.CLog6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.CLog6.setText("")
        self.CLog6.setObjectName("CLog6")
        self.verticalLayout_2.addWidget(self.CLog6)
        self.CLog7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.CLog7.setText("")
        self.CLog7.setObjectName("CLog7")
        self.verticalLayout_2.addWidget(self.CLog7)
        self.CLog8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.CLog8.setText("")
        self.CLog8.setObjectName("CLog8")
        self.verticalLayout_2.addWidget(self.CLog8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 21))
        self.menubar.setObjectName("menubar")
        self.menuAutoLamella = QtWidgets.QMenu(self.menubar)
        self.menuAutoLamella.setObjectName("menuAutoLamella")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAutoLamella.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "Imaging"))
        self.label_17.setText(_translate("MainWindow", " Horizontal Field Width"))
        self.label_18.setText(_translate("MainWindow", "microns"))
        self.RefImage.setText(_translate("MainWindow", "Take Images"))
        self.show_lamella.setText(_translate("MainWindow", "Show Lamella"))
        self.pushButton_3.setText(_translate("MainWindow", "Run Milling"))
        self.label_2.setText(_translate("MainWindow", "0"))
        self.pushButton_4.setText(_translate("MainWindow", "Move to Mill Angle"))
        self.pushButton_2.setText(_translate("MainWindow", "Add Lamella"))
        self.label.setText(_translate("MainWindow", "Selected Lamellas"))
        self.label_11.setText(_translate("MainWindow", "Autolamella"))
        self.ConnectButton.setText(_translate("MainWindow", "Connect to Microscope"))
        self.DisconnectButton.setText(_translate("MainWindow", "Disconnect from Microscope"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.General), _translate("MainWindow", "General"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Stable Movement"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Eucentric Movement"))
        self.label_3.setText(_translate("MainWindow", "Console Log"))
        self.menuAutoLamella.setTitle(_translate("MainWindow", "AutoLamella"))

