# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutoLamellaWorkflowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(385, 280)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.groupBox_workflow = QtWidgets.QGroupBox(Dialog)
        self.groupBox_workflow.setObjectName("groupBox_workflow")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_workflow)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_workflow = QtWidgets.QGridLayout()
        self.gridLayout_workflow.setObjectName("gridLayout_workflow")
        self.gridLayout_3.addLayout(self.gridLayout_workflow, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_workflow, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 1)
        self.label_method = QtWidgets.QLabel(Dialog)
        self.label_method.setObjectName("label_method")
        self.gridLayout.addWidget(self.label_method, 1, 0, 1, 1)
        self.label_header = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setObjectName("label_header")
        self.gridLayout.addWidget(self.label_header, 0, 0, 1, 1)
        self.groupBox_lamella = QtWidgets.QGroupBox(Dialog)
        self.groupBox_lamella.setObjectName("groupBox_lamella")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_lamella)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_lamella = QtWidgets.QGridLayout()
        self.gridLayout_lamella.setObjectName("gridLayout_lamella")
        self.gridLayout_4.addLayout(self.gridLayout_lamella, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_lamella, 2, 0, 1, 1)
        self.label_information = QtWidgets.QLabel(Dialog)
        self.label_information.setObjectName("label_information")
        self.gridLayout.addWidget(self.label_information, 5, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_workflow.setTitle(_translate("Dialog", "Workflow"))
        self.label_method.setText(_translate("Dialog", "Method:"))
        self.label_header.setText(_translate("Dialog", "AutoLamella"))
        self.groupBox_lamella.setTitle(_translate("Dialog", "Lamella"))
        self.label_information.setText(_translate("Dialog", "Estimated Time"))
