# automation config variables

# crosscorrelation
jcut_align_ref_trench:
  xcorr_limit:
    - 100 
    - 100

jcut_align_ref_rotate: 
  xcorr_limit:
  - 512
  - 512 
  - 512
  - 100

jcut_align_ref:
  xcorr_limit:
  - 512
  - 100

jcut_align_ref_eucentric:
  xcorr_limit:
  - 512
  - 100

landing_align_ref:
  xcorr_limit:
  - 512
  - 100

# charge
trench_charge_steps: 20  # EB
jcut_charge_steps: 20    # EB
liftout_charge_steps: 20 # IB
landing_charge_steps: 50 # EB


# step size
liftout_needle_entry_x: 2.0e-6
liftout_needle_entry_z_steps: 2
liftout_needle_contact_x: 0.5e-6
liftout_needle_contact_z: 0.5e-6
liftout_needle_removal_x: 1.5e-6
liftout_needle_removal_z: 10.e-6

landing_needle_removal_x: 0.5e-6

# contact
liftout_brightness_factor: 1.2
liftout_contact_steps: 15

msg:
  confirm_needle_entry: "Has the needle landed on the lamella? \nPress Yes to continue, or No to redo the final movement"